services:
  x-hometl:
    build:
      context: .
    restart: always
    env_file:
      - .env
    networks:
      - misskey_net
      - external_net

networks:
  misskey_net:
    external: true
    name: misskey-orenoheya_internal_network
  external_net:
    driver: bridge
